### PR TITLE
Add height and width values and functions to the term module and get rid off double `#!./buildfiles/et` in `tests/mem_funcs.et`

### PR DESCRIPTION
**Pull request by CanadaHonk**
Also adds tests to the term test script.

### CODE REVIEW

**Comment by CanadaHonk** [comment]
Adds / solves #1.

**Comment by CanadaHonk** [comment]
Also fixes double `#!./buildfiles/et` in `tests/mem_funcs.et` because I accidentally pushed to the same branch :P

**Comment by CanadaHonk** [comment]
Solves #5 as well.

**Comment by Chirag-Khandelwal** [comment]
1. You don't need to use `std::tuple`. Just pass the reference to rows and cols from `term_width` and `term_height` functions to `_term_size` function.
2. It would be better to have a function call when term size is needed since it can change during program's runtime.
3. When you return `new var_*`, you no longer need to pass anything for the `parse_ctr` argument.
4. You may want to test your code by redirecting the execution on your terminal to a file since that shall (by a test I recently did) give wrong row/column size (random numbers).
5. We can directly return a struct from the module function, albeit, it will require a little bit more work.

How about I do these changes? It would also make the code style for the repository apparent :)

**Comment by CanadaHonk** [comment]
Sure. Should the pull request still be merged?

**Comment by Chirag-Khandelwal** [comment]
Unfortunately, since I cannot edit the pull request myself, I won't be able to merge it, especially because I will have to change a lot of the code anyway. Sorry. I hope it is okay :)

**Comment by CanadaHonk** [comment]
It's fine. :)

**Pull request closed without merging**
